spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: microstore
    password: 123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG